server:
  port: 8082

spring:
  application:
    name: auth-api
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  h2:
    console:
      enabled: false
  
  session:
    store-type: redis
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  
  cache:
    type: redis
  
auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:vK*FzP!7s9WqBzE%aLx#RtG2nUj@XhCm}
    expiration: 86400000 # 1 dia em milisegundos

usuario:
  api:
    url: ${USUARIO_API_URL:http://usuario-api:8081/usuario}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    rabbit:
      enabled: false

logging:
  level:
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.http.client: INFO