server:
  port: 8082

spring:
  application:
    name: auth-api

  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  
  session:
    store-type: redis

  data:
    redis:
      host: redis-dev
      port: 6379

  cache:
    type: redis

auth:
  jwt:
    secret: vK*FzP!7s9WqBzE%aLx#RtG2nUj@XhCm
    expiration: 86400000

usuario:
  api:
    url: http://usuario-api:8081/usuario

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    rabbit:
      enabled: false

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG