server:
  port: 8082

spring:
  application:
    name: auth-api

  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

auth:
  jwt:
    secret: vK*FzP!7s9WqBzE%aLx#RtG2nUj@XhCm
    expiration: 86400000

usuario:
  api:
    url: http://localhost:8081/usuario

spring:
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379