server:
  port: 8088
  
spring:
  application:
    name: config-server
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Marcklen/plataforma-fly-configs
          default-label: main
          search-paths: .
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}