spring:
  application:
    name: email-producer-api

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  config:
    activate:
      on-profile: dev

  cloud:
    config:
      enabled: true

server:
  port: 8083

email:
  queue: email.queue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true