spring:
  application:
    name: email-producer-api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  config:
    activate:
      on-profile: dev

  cloud:
    config:
      enabled: true

server:
  port: 8083

email:
  queue: email.queue