spring:
  application:
    name: email-producer-api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  config:
    activate:
      on-profile: dev

  cloud:
    config:
      enabled: true

server:
  port: 8083

email:
  queue: email.queue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}