spring:
  application:
    name: email-consumer-api

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a4962efa143516
    password: 935dadb64b0815
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    activate:
      on-profile: dev

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
