server:
  port: 80

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuario-api
            uri: http://usuario-api:8081
            predicates:
              - Path=/api/usuario/**
            filters:
              - StripPrefix=1
          - id: auth-api
            uri: http://auth-api:8082
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1
