server:
  port: 8080

spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-api
          uri: lb://usuario-api
          predicates:
            - Path=/usuario/**
        - id: auth-api
          uri: lb://auth-api
          predicates:
            - Path=/auth/**
        - id: email-consumer-api
          uri: lb://email-consumer-api
          predicates:
            - Path=/email/**
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}