server:
  port: 8080

spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-api
          uri: lb://usuario-api
          predicates:
            - Path=/usuario/**

        - id: auth-api
          uri: lb://auth-api
          predicates:
            - Path=/auth/**

        - id: email-consumer-api
          uri: lb://email-consumer-api
          predicates:
            - Path=/email/**

        - id: email-producer-api
          uri: lb://email-producer-api
          predicates:
            - Path=/email-producer/**

      # CORS Configuração Glboal
      # globalcors:
      #   cors-configurations:
      #     '[/**]':
      #       allowedOrigins:
      #         - "http://localhost:4200"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders:
      #         - "*"
      #       allowCredentials: true
      #       maxAge: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      # defaultZone: http://host.docker.internal:8761/eureka # Apenas se rodar o Docker atraves do compose

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true