server:
  port: 8081

spring:
  application:
    name: usuario-api

  datasource:
    url: jdbc:h2:mem:usuariodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

auth:
  jwt:
    secret: vK*FzP!7s9WqBzE%aLx#RtG2nUj@XhCm
    expiration: 86400000
